spring.application.name=IfCoders
spring.profiles.active=test
cors.allowed-origins=http://localhost:8080
swagger.url=http://localhost:8080
# chave secreta usada para assinar o token
jwt.secret=mySecretKeySuperSecreta123

# expiração em
# 1 hora de login (comentário separado)
jwt.auth.expiration=3600000
# 30 minutos para confirmar email
jwt.email.expiration=1800000

