spring.application.name=IfCoders
server.address=0.0.0.0
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
swagger.url=${SWAGGER_URL}

jwt.secret=${JWT_SECRET}
jwt.auth.expiration=86400000
jwt.email.expiration=1800000
jwt.reset.expiration=900000 

spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_NAME}
spring.mail.password=${EMAIL_PASSWORD_APP}
link.confirme-token=${LINK_CONFIRME_TOKEN}
link.reset-token=${LINK_RESET_TOKEN}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
aws.bucketName=${S3_BUCKET}
aws.region=${AWS_REGION}
aws.secret.acess.key=${AWS_SECRET_ACCESS_KEY}
aws.access.key=${AWS_ACCESS_KEY_ID}
spring.profiles.active=${PROFILES_ACTIVE}