spring.application.name=IfCoders
spring.profiles.active=test
cors.allowed-origins=http://localhost:8080
swagger.url=http://localhost:8080

jwt.secret=umaChaveMuitoSecretaComPeloMenos32Caracteres123!
jwt.auth.expiration=3600000
jwt.email.expiration=1800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=#coloque seu email
spring.mail.password=#coloque sua senha de app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

